baseurl = "http://dory.me/"
languageCode = "en-us"
title = "Mike Dory | Hi!"
# theme = "hugo-identity-theme"
# theme = "hugo-strata-theme"
theme = "hugo-sustain"


[author]
    name = "Mike Dory"


[params]
    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mike Dory"
    description = "Describe your website"
    avatar = "me-bw-square-tightcrop.jpg"

    # Enable Google Analytics by inserting your tracking code
    googleAnalytics = ""


    [params.sidebar]
        # Replace the avatar with a picture of your own under static/images
        avatar = "avatar.jpg"
        # Use Markdown to format the string. This works nearly all over the theme
        bio = "**Hi! I'm Mike.** I make things and drink coffee."
        # The icons will be shown if you enter your username
        twitter = "mike_dory"
        github = "mikedory"
        dribbble = ""
        facebook = ""

        copyright = [
            "&copy; Mike Dory",
        ]

    [params.about]
        title = "A work in progress, at best."
        content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


[social]
    twitter = "mike_dory"
    email = "mike@dory.me"