baseurl = "http://dory.me/"
languageCode = "en-us"
title = "Mike Dory | Hi!"
theme = "hugo-sustain"
googleanalytics = "UA-34096736-1"


[author]
    name = "Mike Dory"

[menu]
    # [[menu.main]]
    #     name = "about me"
    #     identifier = "about"
    #     url = "/about/"
    [[menu.main]]
        name = "CV"
        identifier = "CV"
        url = "http://linkedin.com/in/mikedory"
    [[menu.main]]
        name = "blog"
        identifier = "blog"
        url = "buh"

[params]
    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mike Dory"
    description = "The personal homepage of Mike Dory."
    avatar = "me-bw-square-tightcrop.jpg"
    resume = "mike-dory-resume.pdf"

[social]
    Twitter = "mike_dory"
    Email = "mike@dory.me"
    LinkedIn = "mikedory"
    Github = "mikedory"
    # Facebook = "michael.dory"