# -----------------------------------
# Jekyll and site config settings
# -----------------------------------

# jekyll setup details
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "migration/", ".gitignore", "Gemfile", "Gemfile.lock"]
auto: false
server: false
pygments: true
server_port: 5000
permalink: /:categories/:title 

# source and deploy deets
source : .
destination : ../public
# plugins:     ./_plugins
production_url : http://dory.me

# analytics
analytics :
  google : 
    tracking_id : 'XX-XXX-XXXX'


# -----------------------------------
# Personalization and details
# -----------------------------------

# all about me
title : dory.me
tagline: Turning coffee into snark and software.
author :
  name : Mike Dory
  github : mikedory
  twitter : mike_dory


# nav bar
nav :
  - title: home
    name: Home
    href : /
    activelink: /index.html
  - title: blog
    name: Blog
    href : http://blog.doryexmachina.com
    activelink: /blog.html
  - title: about
    name: About
    href : about
    activelink: /about.html

# footer links
footer :
  - title: facebook
    href: http://www.facebook.com/michael.dory
    class: icon-facebook-sign
  - title: twitter
    href: http://twitter.com/mike_dory
    class: icon-twitter-sign
  - title: github
    href: http://github.com/mikedory
    class: icon-github-sign
  - title: linkedin
    href: http://www.linkedin.com/in/michaeldory
    class: icon-linkedin-sign
  - title: email
    href: mailto:mike@dory.me
    class: icon-envelope
