# jekyll setup details
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "migration/", ".gitignore", "Gemfile", "Gemfile.lock"]
auto: false
server: false
pygments: true
server_port: 5000

permalink: /:categories/:year/:month/:day/:title 


# all about me
title : dory.me
tagline: Turning coffee into snark and software.
author :
  name : Mike Dory
  github : mikedory
  twitter : mike_dory

# deets
source : .
destination : ../public
# plugins:     ./_plugins
production_url : http://username.github.com

# analytics
analytics :
provider : google 
google : 
    tracking_id : 'XX-XXX-XXXX'

woo : 'yay'